"""Extra scaffolding for readers learning both the mathematics and its English."""

def enhance(pages, section, eq, mat, box, check):
    guides = [
      ('Find numbers that make all the equations true.', 'An equation is like a balance. The left side and the right side must have the same value.', 'Read 2x + y = 7 as: “two times x, plus y, equals seven.”', [('equation','A statement that two amounts are equal.'),('unknown','A number we have not found yet, such as x.'),('solution','A value, or a list of values, that makes every equation true.'),('constraint','A rule that limits the possible answers.')], ['Write down what x and y mean.','Try the answer in both equations.','Use the diagram to see one answer, no answer, or many answers.'], ['Why exactly two solutions cannot happen']),
      ('A matrix is a table of numbers with a particular calculation rule.', 'Start with a two-by-two table. You do not need to understand the general summation formula on the first reading.', 'Read A ∈ ℝ²ˣ³ as: “A is a real matrix with two rows and three columns.”', [('matrix / matrices','One table is a matrix. More than one are matrices.'),('row','A horizontal line of entries: left to right.'),('column','A vertical line of entries: top to bottom.'),('entry','One number in the table.'),('transpose','Exchange the rows and columns.'),('inverse','A matrix that undoes another matrix.')], ['Count rows and columns.','Follow one row-times-column calculation.','Try multiplying a matrix by a two-number vector.'], ['The essential rules']),
      ('Change the equations into an easier form, without changing their answers.', 'Do only one row operation at a time. Write down the arithmetic, including negative signs.', 'Read R₂ ← R₂ − 2R₁ as: “replace row two with row two minus two times row one.”', [('elimination','Removing a variable from an equation by combining equations.'),('pivot','The first nonzero entry of a nonzero row in the staircase form.'),('free variable','A variable you may choose; the other variables then follow.'),('particular solution','One answer that works.'),('general solution','A description of all the answers.')], ['Step through the worked example slowly.','Find which variable is free.','Put the final answer back into the original equations.'], ['The book’s minus-one trick, unpacked','Compute an inverse by solving several systems','What changes on a computer?']),
      ('A vector space is a collection where addition and scaling follow the usual rules.', 'First understand a line through zero. The abstract group definition is a second reading task.', 'Read U ⊆ V as: “U is a subset of V.” Every item in U is also in V.', [('set','A collection of objects.'),('scalar','A single number, used to multiply a vector.'),('space','Here, a collection of vectors with specified operations.'),('closed / closure','The allowed operation keeps you inside the collection.'),('subspace','A smaller collection that is also a vector space.')], ['Read the polynomial example as ordinary addition.','Compare a full line with a half-line.','Test whether a set contains zero and stays closed.'], ['Why the book introduces groups','Build a vector space on that foundation']),
      ('Ask two questions: what can these vectors make, and is any vector unnecessary?', 'A linear combination just means “multiply each vector by a number, then add.”', 'Read αu + βv as: “alpha times u, plus beta times v.” Alpha and beta are just names for numbers.', [('linear combination','A sum of scaled vectors.'),('span','All the vectors you can make with those combinations.'),('dependent','There is an unnecessary vector: the others can build it.'),('independent','No vector can be built from the others.'),('trivial solution','Here, all the coefficients are zero.')], ['Move the two coefficient sliders.','Switch to two directions on the same line.','Explain why three vectors in the example are dependent.'], ['Why a basis makes representations unique','Working with abstract vectors']),
      ('A basis gives enough directions, with no extra ones.', 'A line needs one direction. A plane needs two independent directions. That is the starting idea behind dimension.', 'Read dim(U) = 2 as: “the dimension of U is two.”', [('basis / bases','One basis; several bases. A basis spans the space and is independent.'),('dimension','The number of vectors in a basis.'),('rank','The number of independent columns, or the number of pivots.'),('full rank','The rank is as large as the matrix shape allows.'),('consistent','The equations have at least one solution.')], ['Explain why a line in 3D still has dimension one.','Find pivot columns in the example.','Take the matching columns from the original matrix.'], ['Predict solutions before finding them']),
      ('A linear map changes vectors while respecting addition and scaling.', 'Think of a machine: give it a vector, and it returns another vector. “Map” here means a rule, not a picture of a country.', 'Read Φ(x) as: “phi of x.” It means the output of the rule Φ when its input is x.', [('map / mapping','A rule that gives one output for each input.'),('domain','The collection of allowed inputs.'),('codomain','The stated collection in which outputs live.'),('injective','Different inputs always give different outputs.'),('surjective','Every member of the codomain can be reached.'),('bijective','Both injective and surjective.')], ['Compare shear, stretch, and collapse in the diagram.','See where the two basic arrows go.','Test whether a rule sends zero to zero.'], ['One-to-one, onto, and reversible','Why finite-dimensional spaces become arrays']),
      ('The vector stays the same. Its coordinate numbers can change.', 'An address depends on the reference system. Learn the first numerical example before the general formula.', 'Read [x]ᴮ as: “the coordinates of x in basis B.” Read S⁻¹ as: “S inverse.”', [('coordinate','A coefficient telling you how much of a basis vector to use.'),('ordered basis','A basis with a specified first vector, second vector, and so on.'),('basis change','A change in how the same vectors are described.'),('representation','A way to describe an object using numbers.')], ['Check 2(1,1) + (1,−1) = (3,1).','Move the basis slider while keeping x fixed.','Trace the numerical example by both routes.'], ['Now change the matrix of a map','Equivalence versus similarity']),
      ('The image is what can come out. The kernel is what becomes zero.', 'Write “input space” and “output space” on your paper. Keep the kernel on the input side.', 'Read ker(A) as: “the kernel of A.” Read Im(A) as: “the image of A.”', [('kernel / null space','All input vectors that become the zero vector.'),('image / range','All output vectors the map can produce.'),('nullity','The dimension of the kernel.'),('rank–nullity','Kernel dimension plus image dimension equals input dimension.')], ['Find the outputs in the small matrix example.','Solve its zero-output equations.','Check that the two dimensions add up to three.'], ['Rank–nullity: an accounting identity','An ML interpretation you can already understand']),
      ('Affine means: do a linear operation, then allow a shift.', 'A line through zero is a vector subspace. Slide it away from zero and it is still an affine line.', 'Read p + U as: “p plus U.” It means add the same vector p to every vector in U.', [('affine','Allowing a translation of linear structure.'),('translation','A shift by the same amount and direction.'),('support point','One point used to locate an affine space.'),('direction space','The subspace of directions along an affine space.'),('hyperplane','A space with one fewer dimension than its surrounding space.')], ['Move the line using the slider.','Check whether it still contains zero.','Compare Ax with Ax + a.'], ['Points can be combined, with one extra condition','Linear systems return as affine spaces']),
    ]
    for p,g in zip(pages,guides):
        idea,anchor,spoken,words,tasks,later=g
        helper='<section class="gentle-start"><div class="eyebrow">START SMALL</div><h2>One idea for this lesson</h2><p class="plain-idea">'+idea+'</p><p>'+anchor+'</p><div class="say-it"><strong>How to read the symbols aloud</strong><p>'+spoken+'</p></div><details class="word-help"><summary>English help · words used in this lesson</summary><dl>'+''.join('<dt>'+w+'</dt><dd>'+d+'</dd>' for w,d in words)+'</dl></details><h3>First reading: just these three steps</h3><ol>'+''.join('<li>'+t+'</li>' for t in tasks)+'</ol><p class="caption">You can stop after these steps and the “Pause & predict” question. Return to the formal details when the main idea feels familiar.</p></section>'
        p['body']=helper+p['body']
        for title in later:
            token='<section><h2>'+title+'</h2>'
            replacement='<section class="second-pass"><div class="eyebrow">SECOND READING · MORE DETAIL</div><h2>'+title+'</h2>'
            p['body']=p['body'].replace(token,replacement)
        p['body']=p['body'].replace('An ML interpretation you can already understand','A connection to machine learning')
        p['body']=p['body'].replace('A common elimination trap','A common mistake in elimination')
    primer=section('You can learn this in small pieces','''<p>You are learning two things at once: mathematics and the English used to describe it. A difficult sentence is not proof that the idea is too hard. First translate the sentence into simple words. Then try one small example.</p><p>For now, use a pencil and paper. Read for 10–15 minutes, then stop and try one calculation yourself. You do not need to remember every new word immediately. The lessons have an <strong>English help</strong> box and a <strong>first reading</strong> path. Sections marked <strong>second reading</strong> can wait.</p>''')
    primer+=section('1. A letter is a place for a number','''<p>In 2x + 1 = 7, the letter x stands for a number we want to find. The expression 2x means 2 × x. The multiplication sign is often left out.</p>'''+eq('2x + 1 = 7<br>2x = 6 &nbsp; (subtract 1 from both sides)<br>x = 3 &nbsp; (divide both sides by 2)')+'''<p>Check the answer: 2 × 3 + 1 = 7. The equal sign means “has the same value as.” When changing an equation, do the same thing to both sides.</p>''')
    primer+=section('2. Negative numbers need careful steps','''<p>A minus sign can mean a negative number, or an instruction to subtract. Parentheses show what belongs together.</p>'''+eq('3 − (−2) = 3 + 2 = 5<br>(−2) × 3 = −6<br>(−2) × (−3) = 6')+'''<p>In the last line, two negative factors give a positive product. Now try a calculation that will appear in row operations: 1 − 2(−1). First multiply: 2(−1) = −2. Then subtract: 1 − (−2) = 3. Do not skip that middle step.</p>''')
    primer+=section('3. A fraction is a number too','''<p>The fraction 1/2 means one divided by two. It is the same number as 0.5. Fractions can be useful because they keep calculations exact.</p>'''+eq('½ × 6 = 3<br>½ + ½ = 1<br>x/2 = 3 &nbsp; ⇒ &nbsp; x = 6')+'''<p>In this last line, the symbol ⇒ means “therefore” or “implies.” Multiply both sides by 2 to find x. You cannot divide by zero.</p>''')
    primer+=section('4. A vector is a list of numbers, for now','''<p>Start with the vector (2,1). It has two components: first 2, then 1. On a diagram, start at zero, move 2 units right and 1 unit up. This gives a useful picture of the vector.</p><p>The book usually writes the same numbers vertically:</p>'''+eq('(2,1) &nbsp; written as a column: &nbsp; '+mat([[2],[1]]))+'''<p>Add matching components. Multiply each component when scaling:</p>'''+eq('(2,1) + (3,−1) = (5,0)<br>2(2,1) = (4,2)<br>−1(2,1) = (−2,−1)')+'''<p>A <strong>scalar</strong> is one number, such as 2. A vector has components. Later, the book makes “vector” more general. These small lists are enough to start.</p>''')
    primer+=section('5. Subscripts name a component','''<p>In x₁ and x₂, the small lowered numbers are <strong>subscripts</strong>. They mean “the first component” and “the second component.” They do not mean multiplication.</p><p>If x = (4,7), then x₁ = 4 and x₂ = 7. In contrast, x² is a raised 2 and usually means x times x when x is a scalar. Position matters.</p><p>Greek letters such as α (alpha), β (beta), and λ (lambda) are also just names. In αu + βv, α and β usually stand for scalar numbers.</p>''')
    primer+=section('6. Read a long expression in small pieces','''<p>You will see this kind of sentence:</p>'''+eq('x ∈ ℝ²')+'''<p>Read it as “x is a vector with two real-number components.” The symbol ∈ means “belongs to.” ℝ is the set of real numbers, including numbers such as −3, 0, 1/2, and √2. Here the 2 in ℝ² tells you the number of components; it is not asking you to square a number.</p><p>Now read A ∈ ℝ²ˣ³ as “A is a table of real numbers, with two rows and three columns.” You can replace the symbolic phrase with those words whenever you need to.</p><div class="table-wrap"><table><tr><th>Symbol</th><th>Say it in simple English</th></tr><tr><td>=</td><td>is equal to</td></tr><tr><td>≠</td><td>is not equal to</td></tr><tr><td>∈</td><td>belongs to / is in</td></tr><tr><td>∀</td><td>for every</td></tr><tr><td>∃</td><td>there is at least one</td></tr><tr><td>⇒</td><td>implies / therefore</td></tr><tr><td>⇔</td><td>if and only if; the statement works in both directions</td></tr><tr><td>∑</td><td>add all the listed terms</td></tr></table></div>''')
    primer+=section('7. What does “show that” ask you to do?','''<p>“Calculate” asks you to find a value. “Show that” or “prove” asks you to explain why a statement must be true. Trying a few examples may help you understand, but it does not prove a statement about every possible input.</p><p>To show a universal claim is false, however, one failing example is enough. The claim “every vector in ℝ² has a positive first component” is false because (−1,2) does not. Such an example is called a <strong>counterexample</strong>.</p><p>“If P, then Q” says: whenever P holds, Q follows. It does not automatically say that Q implies P. “If and only if” asserts both directions.</p>''')
    primer+=check('Try three small checks: solve 3x + 2 = 11; calculate (1,−2) + (3,5); calculate 2(1,−2).','For the equation, subtract 2 on both sides first. For the vectors, work on matching components.','The answers are x = 3, (4,3), and (2,−4). If any step is unclear, reread only that part above. These are the basic actions used in the first lesson.')
    return dict(slug='00-start',title='Before Chapter 2',subtitle='Small math steps. Simple English. No hurry.',ref='A gentle starting point',pp='17–18',minutes=15,body=primer,take='You can read a simple equation, work with negative numbers, and add or scale a two-number vector.')
