from pathlib import Path
from html import escape
ROOT=Path(__file__).parent
pages=[]
def eq(s): return '<div class="equation">'+s+'</div>'
def mat(rows): return '<span class="matrix" role="math" aria-label="Matrix: '+escape('; '.join(', '.join(map(str,r)) for r in rows))+'"><span>'+''.join('<span class="matrix-row">'+''.join('<span>'+str(x)+'</span>' for x in r)+'</span>' for r in rows)+'</span></span>'
def box(title,s,kind='insight'): return f'<aside class="{kind}"><strong>{title}</strong>{s}</aside>'
def check(q,h,a): return '<section class="check"><h3>Pause & predict</h3><p>'+q+'</p><details><summary>Give me a hint</summary><p>'+h+'</p></details><details><summary>Show the reasoning</summary><p>'+a+'</p></details></section>'
def section(title,s): return '<section><h2>'+title+'</h2>'+s+'</section>'
def lab(kind,title,prompt,controls): return f'<section class="lab" data-lab="{kind}"><div class="eyebrow">Interactive notebook</div><h2>{title}</h2><p>{prompt}</p><div class="controls">{controls}</div><svg viewBox="0 0 640 400" role="img" aria-label="{title}"></svg><div class="lab-result" aria-live="polite"></div><p class="caption">Use the controls with your mouse or keyboard. The numbers below the diagram describe its current state.</p></section>'
def slider(name,label,value,lo=-3,hi=3,step=.25): return f'<label>{label} <output data-for="{name}">{value}</output><input type="range" name="{name}" min="{lo}" max="{hi}" step="{step}" value="{value}"></label>'
def select(name,label,options): return f'<label>{label}<select name="{name}">'+''.join(f'<option value="{v}">{t}</option>' for v,t in options)+'</select></label>'
def add(slug,title,subtitle,ref,pp,minutes,body,take): pages.append(dict(slug=slug,title=title,subtitle=subtitle,ref=ref,pp=pp,minutes=minutes,body=body,take=take))

add('01-systems','Equations are constraints','One problem. Three ways to see it.','Introduction · §2.1','17–21',18,
section('Start with a concrete question','''<p>Suppose a workshop makes stools and benches. A stool uses 2 pieces of timber and 1 hour of work; a bench uses 1 piece of timber and 2 hours. You have 7 pieces and 8 hours. How many of each would use both resources exactly?</p><p>Let <i>x</i> count stools and <i>y</i> count benches. Each resource supplies one constraint:</p>'''+eq('2x + y = 7<br>x + 2y = 8')+'''<p>Try <i>x</i> = 2 and <i>y</i> = 3. The timber equation gives 4 + 3 = 7, and the time equation gives 2 + 6 = 8. A <strong>solution must satisfy every equation at once</strong>. A pair that satisfies only one constraint is not a solution of the system.</p><p>The chapter’s production example uses the same structure with many resources and products. Real production may also need nonnegative or integer quantities; the linear equations alone do not enforce those restrictions.</p>''')+
section('The row view: intersect constraints','''<p>An equation <i>ax + by = c</i>, with at least one of <i>a</i> or <i>b</i> nonzero, describes a line. With three unknowns a nondegenerate equation describes a plane. Solving the system means finding their common intersection.</p><div class="cards"><article><h3>One solution</h3><p>Independent constraints meet at one point.</p></article><article><h3>No solution</h3><p>Constraints contradict each other.</p></article><article><h3>Infinitely many</h3><p>Some freedom remains after all constraints are satisfied.</p></article></div>''')+
lab('systems','Watch the solution set change','Predict what happens when the second equation becomes a duplicate or a contradiction. The first line is always x + y = 2.',select('mode','Second equation',[('unique','x − y = k'),('parallel','x + y = k')])+slider('k','k',0,-4,4,.5))+
section('The column view: build a target','''<p>Read the same workshop problem in a different direction. Each product contributes a bundle of resources. Can you combine the bundles to make the target?</p>'''+eq('x '+mat([[2],[1]])+' + y '+mat([[1],[2]])+' = '+mat([[7],[8]]))+'''<p>The first column tells you what one stool contributes. The second tells you what one bench contributes. The unknowns are the weights on those columns. This is the beginning of <em>span</em>: everything you can build from the available columns.</p>''')+
section('The matrix view: collect the bookkeeping',eq('A x = b &nbsp; with &nbsp; A = '+mat([[2,1],[1,2]])+', &nbsp; x = '+mat([['x'],['y']])+', &nbsp; b = '+mat([[7],[8]]))+'''<p>In general, <i>A</i> has <i>m</i> rows (equations) and <i>n</i> columns (unknowns). Thus A ∈ ℝ<sup>m×n</sup>, x ∈ ℝ<sup>n</sup>, b ∈ ℝ<sup>m</sup>. The symbol ∈ means “is an element of”; ℝ means the real numbers.</p>'''+box('Keep all three interpretations','<p>Rows impose constraints. Columns offer building blocks. The matrix maps an input x to an output Ax. These are three descriptions of the same calculation.</p>'))+
section('Why exactly two solutions cannot happen','''<p>Suppose distinct vectors p and q both solve Ax = b. By distributing multiplication, every vector p + t(q − p) also solves it:</p>'''+eq('A[p + t(q − p)] = Ap + t(Aq − Ap) = b + t(b − b) = b')+'''<p>For any real <i>t</i> you get a solution. Since p ≠ q, varying <i>t</i> produces infinitely many distinct points. A real linear system therefore has zero, one, or infinitely many solutions.</p>''')+
check('Does having more equations than unknowns guarantee no solution?','Could an equation repeat information already present?','No. For example, x + y = 2, x − y = 0, and 2x + 2y = 4 all hold at (1,1). The third equation is redundant. Consistency and independence matter more than counting equations.'),
'You can translate between equations, column combinations, and Ax = b, and explain the three possible solution outcomes.')

add('02-matrices','Matrices are machines','Learn the rules by asking what they do.','§2.2','22–26',22,
section('Shape first, arithmetic second','''<p>A matrix is a rectangular array. Entry a<sub>ij</sub> is in row <i>i</i>, column <i>j</i>. A 2 × 3 matrix takes a 3-component input and produces a 2-component output. It is helpful to write its job as ℝ³ → ℝ².</p><p>Add matrices of the same shape entry by entry. Scale a matrix by scaling every entry. Multiplication has a different rule because it represents the composition of machines.</p>'''+eq('(m × n)(n × p) → (m × p)')+'''<p>The inner dimensions must match. The outer dimensions give the output shape. For Ax, the shape check is (m × n)(n × 1) = (m × 1).</p>''')+
section('Where row-times-column comes from','''<p>Let A and B be the following machines. To find the first column of AB, feed the first column of B through A. Repeat for the second column.</p>'''+eq('A = '+mat([[1,2],[0,1]])+' &nbsp; B = '+mat([[2,0],[1,3]])+' &nbsp; AB = '+mat([[4,6],[1,3]]))+'''<p>Entry (1,2) means “row 1, column 2.” Its value is 1·0 + 2·3 = 6. Here the dot means multiplication.</p><details><summary>Show every small step of this product</summary><p>Top left: 1×2 + 2×1 = 2 + 2 = 4.<br>Top right: 1×0 + 2×3 = 0 + 6 = 6.<br>Bottom left: 0×2 + 1×1 = 0 + 1 = 1.<br>Bottom right: 0×0 + 1×3 = 0 + 3 = 3.</p><p>Put these four answers in their matching positions. The result is [[4,6],[1,3]].</p></details><p>The following formula says the same thing for a larger matrix. You may return to it later:</p>'''+eq('(AB)<sub>ij</sub> = ∑<sub>k=1</sub><sup>n</sup> a<sub>ik</sub>b<sub>kj</sub>')+'''<p>The summation sign means “add the following terms over the listed index.” The shared index <i>k</i> runs along row <i>i</i> of A and down column <i>j</i> of B.</p>'''+box('Why order matters','<p>ABx means B acts first, then A. For these matrices BA = [[2,4],[1,5]], which differs from AB. A horizontal shear followed by a stretch need not equal the reverse order.</p>'))+
section('The essential rules','''<div class="table-wrap"><table><thead><tr><th>Rule</th><th>Meaning / condition</th></tr></thead><tbody><tr><td>(AB)C = A(BC)</td><td>Regroup compatible products, but keep the order.</td></tr><tr><td>A(B + C) = AB + AC</td><td>Distribute, with matching shapes.</td></tr><tr><td>I<sub>m</sub>A = AI<sub>n</sub> = A</td><td>Identity has ones on the diagonal and zeros elsewhere.</td></tr><tr><td>(AB)ᵀ = BᵀAᵀ</td><td>Transpose reverses product order.</td></tr><tr><td>(A + B)ᵀ = Aᵀ + Bᵀ</td><td>Transpose distributes over addition.</td></tr><tr><td>(AB)⁻¹ = B⁻¹A⁻¹</td><td>For invertible square A and B; undo the last action first.</td></tr></tbody></table></div><p>Scalar factors can move through a matrix product: λ(AB) = (λA)B = A(λB). But (A + B)⁻¹ generally does <em>not</em> equal A⁻¹ + B⁻¹. There is no general rule that lets you divide by a matrix.</p>''')+
section('Transpose is a change of layout','''<p>Transpose exchanges rows and columns: a<sub>ij</sub> becomes a<sub>ji</sub>. A column vector x becomes a row vector xᵀ. Transposing twice gives the original array.</p>'''+eq(mat([[1,2,3],[4,5,6]])+'<sup>T</sup> = '+mat([[1,4],[2,5],[3,6]]))+'''<p>A square matrix is <strong>symmetric</strong> when Aᵀ = A. Sums of symmetric matrices remain symmetric; products need not, because (AB)ᵀ = BA for symmetric A and B. Their product is symmetric exactly when AB = BA.</p><p>For column vectors u,v ∈ ℝⁿ, uᵀv is a scalar, while uvᵀ is an n × n matrix. The bare product uv is not a compatible matrix product except in the scalar case. Elementwise array multiplication is a separate operation, the Hadamard product.</p>''')+
section('An inverse undoes the machine','''<p>A square matrix A is invertible if a matrix A⁻¹ satisfies both AA⁻¹ = I and A⁻¹A = I. “Regular” and “nonsingular” mean invertible. “Singular” means not invertible. A machine that merges distinct inputs cannot have an inverse: it has lost the information needed to recover which input you supplied.</p>'''+eq(mat([['a','b'],['c','d']])+'<sup>−1</sup> = 1/(ad − bc) '+mat([['d','−b'],['−c','a']])+' &nbsp; if ad − bc ≠ 0')+'''<p>For A = [[2,1],[1,1]], ad − bc = 1, so A⁻¹ = [[1,−1],[−1,2]]. Multiplying verifies that both products give I. The quantity ad − bc is the 2 × 2 determinant; the general theory comes in Chapter 4.</p>''')+
check('A has shape 2 × 3 and B has shape 3 × 4. Which of AB and BA exists?','Check the neighboring dimensions separately.','AB exists and has shape 2 × 4. BA would require 4 = 2, so it is undefined. Do not confuse an undefined product with a zero product.'),
'You can check shapes, compute products, and distinguish transpose, inverse, and elementwise multiplication.')

add('03-elimination','Solve without guessing','Expose pivots, contradictions, and freedom.','§2.3','27–35',28,
section('Why row operations are legal','''<p>Gaussian elimination rewrites a system without changing its solution set. Use the augmented matrix [A | b] so that each operation changes both sides of an equation.</p><ol><li>Swap two rows: change the order of the constraints.</li><li>Multiply a row by a <strong>nonzero</strong> scalar: an equivalent equation.</li><li>Add a multiple of one row to another: R<sub>i</sub> ← R<sub>i</sub> + cR<sub>j</sub>, for i ≠ j.</li></ol><p>Each action is reversible. Multiplying a row by zero is forbidden because it destroys information. Arbitrary column operations change the interpretation of the unknowns and are not ordinary row elimination.</p>''')+
section('A worked example, one operation at a time','''<p>We will solve x + 2y − z = 1 and 2x + 5y + z = 5. Predict the next row before stepping forward.</p><div class="elimination"><div class="controls"><button type="button" id="elim-prev">Previous step</button><button type="button" id="elim-next">Next step</button><button type="button" id="elim-reset">Reset</button></div><div id="elim-view" aria-live="polite"></div></div><noscript><p>[1 2 −1 | 1; 2 5 1 | 5] → [1 2 −1 | 1; 0 1 3 | 3] → [1 0 −7 | −5; 0 1 3 | 3]. Thus x = −5 + 7t, y = 3 − 3t, z = t.</p></noscript>''')+
section('Read the staircase of nonzero entries','''<p>A <strong>pivot</strong> is the first nonzero entry in a nonzero row. In row-echelon form (REF), zero rows lie at the bottom and each pivot is farther right than the pivot above it. This makes back-substitution possible.</p><p>Reduced row-echelon form (RREF) adds two requirements: each pivot equals 1, and every other entry in that pivot’s column is zero. In our example, columns 1 and 2 are pivot columns. Variables x and y are basic variables; z is free.</p><p>A row [0 0 0 | 5] says 0 = 5: <strong>stop, no solution</strong>. A row [0 0 0 | 0] contributes no constraint. Only coefficient columns correspond to variables; a pivot in the augmented column signals inconsistency.</p>''')+
section('One solution, plus changes that keep it a solution',eq('x = '+mat([[-5],[3],[0]])+' + t '+mat([[7],[-3],[1]])+' &nbsp; t ∈ ℝ')+'''<p>Setting the free variable to zero gives a particular solution p = (−5,3,0). The direction z = (7,−3,1) solves Az = 0: 7 − 6 − 1 = 0 and 14 − 15 + 1 = 0. Therefore adding any multiple of it leaves the output unchanged.</p>'''+box('The general solution','<p>If Ap = b, every solution is p + z with Az = 0. Proof: A(p + z) = b. Conversely, if Ax = b, then A(x − p) = 0. This proves both that the formula works and that it misses no solutions. The solution set is unique; its choice of particular point and spanning directions need not be.</p>'))+
section('The book’s minus-one trick, unpacked','''<p>The trick on pp. 32–33 is a compact way to construct null-space directions from RREF. It is easiest to understand by choosing one free variable at a time.</p>'''+eq('R = '+mat([[1,2,0,3],[0,0,1,-1]]))+'''<p>The equations are x₁ + 2x₂ + 3x₄ = 0 and x₃ − x₄ = 0. Free variables are x₂ and x₄. Choose (x₂,x₄) = (−1,0) to get (2,−1,0,0), and (0,−1) to get (3,0,−1,−1).</p>'''+eq('R̃ = '+mat([[1,2,0,3],[0,-1,0,0],[0,0,1,-1],[0,0,0,-1]]))+'''<p>After removing zero rows, insert a row with −1 at each missing diagonal pivot position. Columns 2 and 4 of this expanded array are exactly those two null-space vectors. Choosing +1 instead simply reverses their signs; either basis works. This expanded array is a reading aid, not an equivalent augmented equation system.</p>''')+
section('Compute an inverse by solving several systems','''<p>For a square matrix, apply the same row operations to [A | I]. If the left block becomes I, the right block becomes A⁻¹. Each identity column is a different right-hand side, so you are solving all columns of AX = I simultaneously.</p>'''+eq('[ '+mat([[1,1],[1,2]])+' | I ] → [ I | '+mat([[2,-1],[-1,1]])+' ]')+'''<p>Here subtract row 1 from row 2, then subtract the new row 2 from row 1. If the left block cannot become I, A is singular.</p>''')+
section('What changes on a computer?','''<p>For hand calculations, elimination reveals structure. In numerical work, pivot selection helps control rounding error. Solving Ax = b directly is generally preferable to explicitly constructing A⁻¹.</p><p>If A has independent columns, AᵀA is invertible. For a consistent system, x = (AᵀA)⁻¹Aᵀb is its solution. For an inconsistent system, this formula gives the unique least-squares minimizer instead; it does not make the original equations true. The book discusses this full-column-rank form of the pseudoinverse, not a formula valid for every matrix.</p><p>Dense elimination for n × n systems takes arithmetic work proportional to n³. Large structured systems may use iterative solvers. The book sketches x<sup>(k+1)</sup> = Cx<sup>(k)</sup> + d; convergence needs suitable C, not an arbitrary choice. The error x<sup>(k)</sup> − x* and the residual b − Ax<sup>(k)</sup> are different quantities. Iterative methods and least squares are context here, not prerequisites for the rest of Chapter 2.</p>''')+
check('A consistent system has 5 unknowns and 3 pivots. How many free parameters remain?','Each pivot determines one basic variable.','Two. Set each free variable independently; solve for the three basic variables. The solution set is a two-dimensional affine space, even though each solution has five entries.'),
'You can row-reduce, identify inconsistency, and express every solution as a particular point plus null-space directions.')

add('04-spaces','What makes something a vector?','Addition and scaling matter more than arrows.','§2.4','35–40',22,
section('A vector is an object with a consistent algebra','''<p>An arrow is one model of a vector. A polynomial, an audio sample array, or an image can also be a vector. What matters is that addition and scalar multiplication obey the vector-space rules.</p><p>For example, let p(t) = 1 + 2t and q(t) = 3 − t. Then p + q = 4 + t and 2p = 2 + 4t. All remain in the space of polynomials of degree at most 1. Their coordinates relative to (1,t) are (1,2), (3,−1), (4,1), and (2,4).</p>'''+box('Closure is necessary, but not the whole definition','<p>Staying in the same set is only the first requirement. The operations must also satisfy the group and scalar rules below. A custom operation that happens to be closed does not automatically make a vector space.</p>'))+
section('Why the book introduces groups','''<p>A group describes one operation that can be performed and undone consistently. For a set G and an operation ★, require:</p><div class="table-wrap"><table><tr><th>Property</th><th>What to check</th></tr><tr><td>Closure</td><td>a ★ b stays in G.</td></tr><tr><td>Associativity</td><td>(a ★ b) ★ c = a ★ (b ★ c).</td></tr><tr><td>Identity</td><td>Some e leaves every element unchanged on either side.</td></tr><tr><td>Inverse</td><td>Each a has an element that combines with it to give e on either side.</td></tr></table></div><p>If a ★ b = b ★ a as well, the group is <strong>Abelian</strong>. Integers under addition form an Abelian group: the identity is 0 and the inverse of 3 is −3. Nonnegative integers fail because −3 is missing. Nonzero reals under multiplication form an Abelian group with identity 1 and inverse 1/a.</p><p>All n × n matrices under multiplication do not form a group: singular matrices lack inverses. The invertible ones form GL(n,ℝ). This is generally non-Abelian for n ≥ 2; GL(1,ℝ) is Abelian.</p>''')+
section('Build a vector space on that foundation','''<p>A real vector space first needs an Abelian group under addition. That supplies closure, associativity, an additive zero, additive inverses, and commutativity. Scalar multiplication must be closed and satisfy:</p>'''+eq('λ(u + v) = λu + λv<br>(λ + μ)v = λv + μv<br>λ(μv) = (λμ)v<br>1v = v')+'''<p>These rules justify distributing and regrouping the expressions used throughout the chapter. They imply 0v = 0, λ0 = 0, and (−1)v = −v. The first zero in 0v is a scalar; the output zero is the vector-space zero.</p><p>The scalar field matters. Complex numbers form a two-dimensional vector space over ℝ, with basis (1,i), but a one-dimensional space over ℂ. This guide follows the chapter’s real-scalar setting.</p>''')+
section('Subspaces: smaller worlds with the same rules','''<p>A subset U of an existing vector space V inherits most algebraic laws. You only need to show that it contains zero and is closed under addition and arbitrary real scaling. Equivalently, check that U is nonempty and αu + βv ∈ U whenever u,v ∈ U and α,β ∈ ℝ.</p><div class="cards"><article><h3>Yes: a line through zero</h3><p>{t(1,2) : t ∈ ℝ}. Adding or scaling changes only t.</p></article><article><h3>No: a shifted line</h3><p>{(x,y) : y = 2x + 1}. It excludes (0,0).</p></article><article><h3>No: a half-line</h3><p>{t(1,2) : t ≥ 0}. Negative scaling leaves the set.</p></article></div><p>Containing zero alone is insufficient: the union of the coordinate axes contains zero, but (1,0) + (0,1) = (1,1) lies on neither axis. Intersections of subspaces are subspaces, because every closure condition holds in each participating space.</p>''')+
section('Why homogeneous systems always give subspaces','''<p>Let U = {x : Ax = 0}. It contains zero. If Au = Av = 0, then A(αu + βv) = αAu + βAv = 0. So all linear combinations stay inside U.</p><p>Conversely, every subspace of ℝⁿ can be described by some homogeneous linear system. This connects a geometric description (“a line through zero”) with an algebraic one (“solutions of these equations”).</p>''')+
check('Do all polynomials of degree exactly 2 form a vector space?','Add t² and −t².','No: their sum is the zero polynomial, which has no degree 2. Polynomials of degree at most 2, including zero, do form a vector space. A description with a nonlinear-looking parameter also need not fail: in the book’s Exercise 2.9(a), μ³ ranges over every real number.'),
'You can test a subspace and recognize vectors beyond geometric arrows, while keeping the scalar field and operations explicit.')

add('05-independence','Span and independence','What can we make? Is anything unnecessary?','§2.5 · §2.6.1','40–45',20,
section('A span is everything your ingredients can build','''<p>A linear combination uses scalar weights: v = α₁v₁ + ⋯ + αₖvₖ. Its weights may be positive, negative, or zero. The <strong>span</strong> is the set of all results as those weights vary freely.</p><p>One nonzero vector spans a line through zero. Two nonparallel vectors in ℝ² span the plane. Two parallel vectors still span only a line. In ℝ³, two independent vectors span a plane, not all of ℝ³.</p>''')+
lab('span','Build a vector from two directions','Change the coefficients. Then make the directions dependent: what outputs become unreachable?',select('mode','Available directions',[('independent','u = (1,0), v = (1,1)'),('dependent','u = (1,0), v = (2,0)')])+slider('alpha','α',1)+slider('beta','β',1))+
section('Independence is a test for redundant ingredients',eq('α₁v₁ + ⋯ + αₖvₖ = 0 &nbsp; ⇒ &nbsp; α₁ = ⋯ = αₖ = 0')+'''<p>If this implication holds, the vectors are independent. If any nonzero list of coefficients produces zero, they are dependent. “Nontrivial” means <em>at least one</em> coefficient is nonzero, not that every coefficient must be nonzero.</p><p>Why test against zero? If α₁v₁ + ⋯ + αₖvₖ = 0 and αⱼ ≠ 0, rearrange to express vⱼ using the others. It adds no new reach. Conversely, any such redundant expression can be moved to one side to produce a nontrivial zero combination.</p>''')+
section('A small example that prevents a big misconception','''<p>Take u = (1,0), v = (0,1), and w = (1,1). No pair is parallel, but u + v − w = 0. The three vectors are dependent.</p>'''+box('Pairwise nonparallel is not enough','<p>For two nonzero vectors, dependence means one is a scalar multiple of the other. With three or more vectors, dependence may involve several vectors at once. Any set containing zero is dependent, since 1·0 already supplies a nontrivial relation.</p>')+'''<p>Put the vectors into the columns of A and solve Aα = 0. A pivot in every column means independence. A free variable means dependence. You only need REF to identify pivots.</p>'''+eq('A = '+mat([[1,0,1],[0,1,1]])+' &nbsp; ⇒ &nbsp; α = t '+mat([[-1],[-1],[1]])))+
section('Why a basis makes representations unique','''<p>Suppose the same output has two coefficient lists: ∑αᵢvᵢ = ∑βᵢvᵢ. Subtract to obtain ∑(αᵢ − βᵢ)vᵢ = 0. Independence forces every αᵢ − βᵢ to be zero. Therefore the lists are identical.</p><p>This argument explains why independence is about uniqueness, while spanning is about existence. A basis will need both.</p>''')+
section('Working with abstract vectors','''<p>Suppose b₁,…,bₖ are independent, and xⱼ = ∑ᵢ λᵢⱼbᵢ. You can test the xⱼ by testing their coordinate columns λⱼ. A zero combination of the xⱼ becomes a zero combination of the bᵢ; independence of the bᵢ forces the combined coordinates to vanish.</p><p>This is the method behind the book’s Example 2.15. It also means more than k linear combinations of k vectors must be dependent. In a two-dimensional space, a third vector cannot supply a third independent direction.</p>''')+
check('Are p(t) = 1 + t and q(t) = 1 − t independent?','Set αp + βq = 0 and compare the constant and t coefficients.','Yes. The constant term gives α + β = 0; the t coefficient gives α − β = 0. Hence α = β = 0. These two polynomials span all polynomials of degree at most 1.'),
'You can distinguish the set of reachable vectors from the uniqueness of the coefficients used to reach them.')

add('06-basis','Basis, dimension, and rank','Count independent directions, not entries.','§2.6','44–48',22,
section('A basis is an exact set of ingredients','''<p>A basis of V is an independent set that spans V. Spanning guarantees that every vector has coordinates; independence guarantees that the coordinates are unique.</p><p>Equivalently, it is a minimal generating set: remove any vector and something becomes unreachable. It is also a maximal independent set within V: add another vector from V and redundancy appears.</p><p>The standard basis of ℝ³ is (1,0,0), (0,1,0), (0,0,1). But (1,0,0), (1,1,0), (1,1,1) is another basis. Basis vectors need not be perpendicular or have length 1.</p>''')+
section('Dimension counts directions','''<p>All bases of a finite-dimensional space have the same number of vectors. That number is its dimension. A line in ℝ³ has dimension 1 even though its vectors have three entries. The space of 2 × 3 matrices has dimension 6, because each of six entries can vary independently.</p><p>The space containing only zero has dimension 0 and the empty basis. If U ⊆ V are finite-dimensional subspaces, dim U ≤ dim V; equality forces U = V.</p>''')+
section('Extract a basis without losing the original space',eq('A = '+mat([[1,2,0],[1,2,1],[0,0,1]])+' &nbsp; → &nbsp; R = '+mat([[1,2,0],[0,0,1],[0,0,0]]))+'''<p>Columns 1 and 3 contain pivots. Take columns 1 and 3 <strong>from the original A</strong>: (1,1,0) and (0,1,1). They form a basis of its column space; column 2 is twice column 1.</p>'''+box('A common elimination trap','<p>Row operations preserve dependence relations among columns, but generally move the column space itself. The reduced columns (1,0,0) and (0,1,0) are not a basis of the original column space here. Use the reduced matrix to find column indices; use A to retrieve the vectors.</p>'))+
section('Rank counts the useful directions','''<p>The rank r of an m × n matrix is the dimension of its column space. It also equals its row-space dimension and the number of pivots. Row rank and column rank are equal, although the row space lives in ℝⁿ and the column space lives in ℝᵐ.</p>'''+eq('rank(A) = rank(Aᵀ) ≤ min(m,n)')+'''<p>A basis for the row space can be read from the nonzero rows of REF. Alternatively, find pivot columns of Aᵀ and take the corresponding original rows of A.</p><p>“Full rank” means r = min(m,n). A tall full-rank matrix has independent columns. A wide full-rank matrix has independent rows. Only a <em>square</em> full-rank matrix has a two-sided inverse.</p>''')+
section('Predict solutions before finding them','''<div class="table-wrap"><table><tr><th>Rank condition</th><th>Consequence for Ax = b</th></tr><tr><td>rank([A | b]) &gt; rank(A)</td><td>No solution: b supplies a direction outside the column span.</td></tr><tr><td>rank([A | b]) = rank(A) = n</td><td>Exactly one solution: consistent, with no free variables.</td></tr><tr><td>rank([A | b]) = rank(A) &lt; n</td><td>Infinitely many solutions: n − r free parameters.</td></tr></table></div><p>For the A above, the output is (x₁ + 2x₂, x₁ + 2x₂ + x₃, x₃). Thus b must satisfy b₂ = b₁ + b₃. If it does, one free parameter remains. If it does not, elimination reveals a contradiction.</p>''')+
check('A 4 × 6 matrix has rank 4. Is Ax = b solvable for every b ∈ ℝ⁴? Is the solution unique?','The image has dimension 4. There are 6 input variables.','Every b is reachable, since the column space is all of ℝ⁴. Each system has two free parameters, so no solution is unique. Full row rank gives surjectivity, not injectivity.'),
'You can extract a basis correctly, interpret rank, and use rank conditions to classify a linear system.')

add('07-maps','Linear maps preserve combinations','Knowing where the basis vectors go tells us the whole rule.','§2.7 · §2.7.1','48–53',23,
section('Linearity is a promise about structure',eq('Φ(αu + βv) = αΦ(u) + βΦ(v)')+'''<p>This must hold for every u,v and every real α,β. It says you get the same answer whether you combine inputs before applying Φ or combine their outputs afterward.</p><p>Every matrix map x ↦ Ax is linear because multiplication distributes and respects scaling. Differentiation is linear on an appropriate function space: (αf + βg)′ = αf′ + βg′. Integration over fixed bounds is linear too.</p><p>A linear map must send zero to zero. That is a useful rejection test: x ↦ Ax + b with b ≠ 0 is not linear. But passing this test alone does not prove linearity: x ↦ x² sends zero to zero and fails additivity.</p>''')+
lab('transform','See what the matrix does','The teal arrow is Ae₁, the gold arrow is Ae₂, and the coral arrow is A(1,1). The faint square and grid show the original coordinates.',select('preset','Transformation',[('shear','Shear'),('rotate','Rotate 45°'),('stretch','Stretch'),('collapse','Collapse onto a line'),('reflect','Reflect')]))+
section('Columns record the images of basis vectors','''<p>In standard coordinates, x = x₁e₁ + ⋯ + xₙeₙ. Apply linearity:</p>'''+eq('Φ(x) = x₁Φ(e₁) + ⋯ + xₙΦ(eₙ)')+'''<p>So build A by putting Φ(eⱼ) into column j. That is why a matrix stores everything about a linear map. If Φ(e₁) = (2,1) and Φ(e₂) = (−1,3), then:</p>'''+eq('A = '+mat([[2,-1],[1,3]])+' &nbsp; and &nbsp; Φ(3,2) = 3(2,1) + 2(−1,3) = (4,9)')+'''<p>For arbitrary input basis B and output basis C, the rule becomes: column j is the <em>C-coordinate vector</em> of Φ(bⱼ). This distinction matters in the next lesson.</p>''')+
section('One-to-one, onto, and reversible','''<div class="table-wrap"><table><tr><th>Name</th><th>Meaning</th><th>For A ∈ ℝ<sup>m×n</sup></th></tr><tr><td>Injective</td><td>Different inputs have different outputs.</td><td>rank A = n</td></tr><tr><td>Surjective</td><td>Every point in the stated codomain is reached.</td><td>rank A = m</td></tr><tr><td>Bijective</td><td>Both; every output has exactly one input.</td><td>m = n = rank A</td></tr></table></div><p>The codomain is part of the definition. The map t ↦ (t,0) is injective, but is not onto ℝ². With its codomain restricted to the horizontal axis, it is bijective.</p><p>A linear map is also called a homomorphism. A bijective linear map is an <strong>isomorphism</strong>. A linear map from a space to itself is an <strong>endomorphism</strong>; if also bijective, an <strong>automorphism</strong>.</p>''')+
section('Why finite-dimensional spaces become arrays','''<p>Two finite-dimensional real vector spaces are isomorphic exactly when they have the same dimension. Choosing a basis constructs the isomorphism: send the coefficient list (α₁,…,αₙ) to ∑αᵢbᵢ.</p><p>Thus polynomials of degree at most 2 and ℝ³ have the same linear structure. This does not automatically identify their lengths or angles; those require extra structure in Chapter 3.</p><p>Composing linear maps gives another linear map. If Φ has matrix A and Ψ has matrix B, with compatible intermediate coordinates, Ψ ∘ Φ has matrix BA. Sums and scalar multiples of maps with the same domain and codomain are also linear. A bijective linear map has a linear inverse.</p>''')+
check('Is Φ(x,y) = (x + y, 2x + 2y) injective?','Can different inputs have the same sum?','No. (1,0) and (0,1) both map to (1,2). The difference (1,−1) maps to zero. Its image is the line spanned by (1,2), so it is also not onto ℝ².'),
'You can test linearity, build a transformation matrix, and distinguish injectivity from surjectivity.')

add('08-coordinates','Same vector, new coordinates','Derive the basis-change formula instead of memorizing it.','§2.7.1–2.7.2','50–58',30,
section('The object and its address are different','''<p>Let B be the ordered basis b₁ = (1,1), b₂ = (1,−1). The vector x = (3,1) has B-coordinates (2,1), because 2(1,1) + 1(1,−1) = (3,1).</p><details><summary>How did we find the numbers 2 and 1?</summary><p>Call the unknown coordinates a and b. We need a(1,1) + b(1,−1) = (3,1).</p><p>The first components give a + b = 3. The second components give a − b = 1. Add these equations: 2a = 4, so a = 2. Then 2 + b = 3, so b = 1.</p><p>The vector is (3,1) in standard coordinates. The list (2,1) tells us how much of each new basis vector to use.</p></details><p>Write [x]<sub>B</sub> for the coordinate list and P<sub>B</sub> for the matrix whose columns are the basis vectors in standard coordinates. Then:</p>'''+eq('x = P<sub>B</sub>[x]<sub>B</sub> &nbsp; and &nbsp; [x]<sub>B</sub> = P<sub>B</sub>⁻¹x')+'''<p>The inverse is valid here because B is a basis of all of ℝⁿ. For a k-dimensional subspace of ℝⁿ with k &lt; n, the basis matrix is rectangular; find coordinates by solving P<sub>B</sub>α = x within that subspace instead.</p><p>Order matters. Swapping b₁ and b₂ swaps the two coordinates. The book uses B for both an ordered basis and, in other contexts, its column matrix; this guide uses P<sub>B</sub> when the distinction helps.</p>''')+
lab('basis','Keep the vector. Change its address.','The coral vector x stays fixed while the second basis direction changes. Predict its coordinates before moving the slider.',slider('shear','s in b₂ = (s,1)',1,-2,2,.25)+slider('x','x₁',2,-3,3,.5)+slider('y','x₂',1,-3,3,.5))+
section('Coordinate conversion has a direction','''<p>If B and D are bases in standard coordinates, the matrix converting D-coordinates to B-coordinates is:</p>'''+eq('[x]<sub>B</sub> = P<sub>B</sub>⁻¹P<sub>D</sub>[x]<sub>D</sub>')+'''<p>Read right to left: P<sub>D</sub> turns the D-address into the actual standard-coordinate vector; P<sub>B</sub>⁻¹ expresses that vector in B. The columns of the conversion matrix are the D basis vectors expressed in B.</p>'''+box('Attach input and output labels','<p>“Change from B to D” can be ambiguous in prose. Write [x]<sub>D</sub> = Q[x]<sub>B</sub> before computing Q. This makes the intended direction checkable and prevents an accidental inverse.</p>'))+
section('Now change the matrix of a map','''<p>Suppose A represents Φ using old input basis B and old output basis C. Let S convert <em>new input coordinates to old input coordinates</em>, and T convert <em>new output coordinates to old output coordinates</em>.</p><div class="route"><span>New input</span><b>→ S →</b><span>Old input</span><b>→ A →</b><span>Old output</span><b>→ T⁻¹ →</b><span>New output</span></div>'''+eq('Ã = T⁻¹AS')+'''<p>Derivation: x<sub>old</sub> = Sx<sub>new</sub> and y<sub>old</sub> = Ty<sub>new</sub>. Substitute these into y<sub>old</sub> = Ax<sub>old</sub>: Ty<sub>new</sub> = ASx<sub>new</sub>. Multiplying by T⁻¹ gives the result. For an m × n A, S is n × n and T is m × m.</p><p>This is Theorem 2.20 in the book. The underlying map Φ has not changed. Only how its inputs and outputs are described has changed.</p>''')+
section('Work the book’s simplifying example',eq('A = '+mat([[2,1],[1,2]])+' &nbsp; S = '+mat([[1,1],[1,-1]]))+'''<p>The new basis vectors are b₁ = (1,1) and b₂ = (1,−1). Apply A directly: Ab₁ = (3,3) = 3b₁, and Ab₂ = (1,−1) = b₂. In the new coordinates, the machine just multiplies the first coordinate by 3 and leaves the second alone.</p>'''+eq('S⁻¹ = ½ '+mat([[1,1],[1,-1]])+' &nbsp; ⇒ &nbsp; S⁻¹AS = '+mat([[3,0],[0,1]]))+'''<p>Check it with x = (3,1). Its new coordinates are (2,1). The diagonal matrix produces (6,1); convert back to get 6b₁ + b₂ = (7,5). Directly, A(3,1) = (7,5). Both routes agree.</p><p>Chapter 4 will explain how to find useful directions like these systematically. For now, understanding why the coordinates simplify is enough.</p>''')+
section('Equivalence versus similarity','''<p>Matrices related by Ã = T⁻¹AS are <strong>equivalent</strong>: input and output bases can change independently. Square matrices related by Ã = S⁻¹AS are <strong>similar</strong>: use the same change of basis for an endomorphism’s input and output.</p><p>Similarity implies equivalence, but the reverse need not hold. For example I and 2I are equivalent, taking S = 2I and T = I, but not similar, since S⁻¹IS = I for every invertible S.</p>''')+
check('A maps standard input coordinates to standard output coordinates. Change only the input basis to columns of S. What is the new matrix?','The output conversion T is the identity.','AS. New input coordinates first become standard coordinates through S, then A acts. If only the output basis changes to T, the result is T⁻¹A.'),
'You can label coordinate conversions, derive T⁻¹AS, and verify a basis change by following one vector along both routes.')

add('09-kernel','What gets through? What disappears?','Image and kernel complete the story of Ax = b.','§2.7.3','58–60',24,
section('Two spaces, on two sides of the machine','''<p>For A : ℝⁿ → ℝᵐ, the <strong>image</strong> is the set of reachable outputs, and the <strong>kernel</strong> is the set of inputs mapped to zero.</p>'''+eq('Im(A) = {Ax : x ∈ ℝⁿ} ⊆ ℝᵐ<br>ker(A) = {x ∈ ℝⁿ : Ax = 0} ⊆ ℝⁿ')+'''<p>The image is the span of A’s columns. The kernel records combinations of those columns that cancel. Both are subspaces, by linearity. The notation Φ⁻¹({0}) for a kernel means the <em>preimage</em> of zero, not that an inverse function exists.</p>''')+
section('Compute both for the same matrix',eq('A = '+mat([[1,0,1],[0,1,1]]))+'''<p>The first two columns are a basis of ℝ², so Im(A) = ℝ² and rank A = 2. To find the kernel, solve x₁ + x₃ = 0 and x₂ + x₃ = 0. Set x₃ = t:</p>'''+eq('ker(A) = span{ '+mat([[-1],[-1],[1]])+' }')+'''<p>The image has dimension 2; the kernel has dimension 1. Notice that the kernel vector has three entries, while each image vector has two. Mixing these ambient spaces is a frequent source of mistakes.</p>''')+
lab('kernel','Move without changing the output','Here A = [[1,1],[2,2]]. Inputs x = (1+t, 1−t) slide along one affine line. Watch their outputs.',slider('t','t',0,-3,3,.25))+
section('Why the kernel measures ambiguity','''<p>If Ax = Ay, subtract to obtain A(x − y) = 0. So two inputs collide exactly when their difference lies in the kernel. This immediately proves:</p>'''+eq('A is injective ⇔ ker(A) = {0}')+'''<p>For any reachable b and any particular solution p, all inputs producing b form p + ker(A). The same kernel describes the freedom in every consistent right-hand side. Changing b moves the solution set; it does not change its direction space.</p>''')+
section('Rank–nullity: an accounting identity',eq('dim ker(A) + dim Im(A) = n')+'''<p>The right side is the <strong>input dimension</strong>. In elimination language there are r pivot variables and n − r free variables. In mapping language r dimensions of output are reachable and n − r independent input directions vanish.</p><details><summary>Why the theorem is true beyond matrices</summary><p>Choose a basis k₁,…,k<sub>d</sub> of the kernel and extend it to a basis of the domain by adding v₁,…,v<sub>r</sub>. The images Φ(vᵢ) span the image because the kᵢ contribute zero. They are independent: a zero combination of their images would put the same combination of vᵢ in the kernel, contradicting independence of the extended basis. Therefore the image has dimension r and the domain has dimension d + r.</p></details><p>When domain and codomain have the same finite dimension, injective, surjective, and bijective become equivalent. When their dimensions differ, those words must be kept separate.</p>''')+
section('An ML interpretation you can already understand','''<p>Think of x as a list of feature weights and Ax as predictions. A nonzero kernel vector z changes weights from x to x + z without changing the predictions. Redundant columns mean the observations cannot distinguish those parameter choices.</p><p>This is a statement about identifiability, before probability or optimization enters. A later method may select one of many weight vectors, but the original equations alone cannot tell them apart.</p>''')+
check('For the 2 × 3 matrix above, find every input giving b = (4,5).','First take x₃ = 0, then add a kernel vector.','A particular solution is (4,5,0). All solutions are (4−t,5−t,t), t ∈ ℝ. Substitution gives (4−t+t,5−t+t) = (4,5). The map is onto ℝ² but not injective.'),
'You can compute image and kernel, keep their ambient spaces straight, and interpret rank–nullity as degrees of freedom.')

add('10-affine','When the origin moves','Finish where you began: the geometry of solutions.','§2.8–2.9','61–63',20,
section('An affine space is a translated subspace',eq('L = p + U = {p + u : u ∈ U}')+'''<p>U is the direction subspace and p is a support point. A line can be written p + td for a nonzero direction d. A plane can be written p + su + tv for independent directions u,v. Its dimension is the dimension of its direction space.</p><p>The support point is not unique: any point on L can play that role. The direction subspace is unique, because differences of points in L recover it. L is a vector subspace exactly when it contains zero, equivalently p ∈ U.</p>''')+
lab('affine','Translate a line away from zero','The line is L = (0,h) + t(1,1). Vary h and compare the line with its direction space.',slider('h','h',1,-3,3,.5))+
section('Points can be combined, with one extra condition','''<p>For points pᵢ in an affine space, an affine combination ∑αᵢpᵢ stays in the space when ∑αᵢ = 1. To see why, write pᵢ = p + uᵢ. Then ∑αᵢpᵢ = p + ∑αᵢuᵢ. Without the sum-to-one condition, the support point is scaled too.</p><p>This is a useful extension of the book’s definition: the midpoint ½p₁ + ½p₂ stays on the line, while p₁ + p₂ need not. Differences of points are direction vectors, so subtracting two solutions removes the offset.</p>''')+
section('Linear systems return as affine spaces','''<p>If Ax = b is consistent, its solution set is p + ker(A), where Ap = b. Thus it is an affine space of dimension n − rank(A). If b = 0, it is the kernel itself. If the equations contradict each other, the solution set is empty.</p><p>A <strong>hyperplane</strong> in ℝⁿ has dimension n − 1. One scalar equation aᵀx = c with a ≠ 0 defines a hyperplane. A general consistent vector equation Ax = b can have higher codimension; it is a hyperplane only when rank(A) = 1.</p>'''+box('Read the rank condition carefully','<p>The broad hyperplane wording in the remark on printed p. 62 needs this qualification. For example, two independent constraints in ℝ³ typically leave a line of dimension 1, not a hyperplane of dimension 2.</p>')+'''<p>For containment, p + U ⊆ q + W exactly when U ⊆ W and p − q ∈ W. The directions must fit, and the support point must lie in the larger affine space.</p>''')+
section('Affine maps: transform, then translate',eq('f(x) = Ax + a')+'''<p>A is the linear part and a is the translation vector. Since f(0) = a, this map is linear exactly when a = 0. Much ML terminology calls a layer “linear” even when it includes a bias; mathematically its pre-activation map is affine.</p><p>If g(y) = By + b, composition gives:</p>'''+eq('g(f(x)) = B(Ax + a) + b = (BA)x + (Ba + b)')+'''<p>So a composition of affine maps is affine. If A is invertible, the inverse is f⁻¹(y) = A⁻¹(y − a). Invertible affine maps preserve dimension and parallelism, but generally do not preserve lengths or angles. Noninvertible affine maps can collapse lines or planes.</p>''')+
section('Where Chapter 2 ends','''<p>You now have the language of linear structure: combinations, constraints, bases, maps, and their dimensions. Chapter 3 adds an inner product and uses it to measure lengths, angles, distances, and orthogonality. Do not assume every basis is orthonormal just because we drew its vectors on a familiar grid.</p><p>Section 2.9 points toward more linear algebra and numerical linear algebra texts. For this reading session, the best next step is to use the practice page to find any weak connection, then return to the corresponding section in your PDF.</p>''')+
check('Is f(x,y) = (x + 2, y − 1) linear? Is it invertible?','Test the origin. Then try to undo the shift.','It is affine, not linear: f(0,0) = (2,−1). It is invertible, with f⁻¹(u,v) = (u−2,v+1). Being reversible does not by itself imply linearity.'),
'You can distinguish linear and affine spaces and maps, and recover the geometry of every consistent linear system.')
exercise_data=[
('2.1','64','Groups with an unfamiliar operation','04-spaces','Rewrite a ★ b + 1 as (a + 1)(b + 1). This converts the operation into ordinary multiplication on nonzero real numbers.','The identity is 0, and the inverse of a is −a/(a+1). Closure follows because (a+1)(b+1) cannot be zero. Associativity and commutativity follow from multiplication. The equation becomes 4(x+1)² = 16, giving x = 1 or x = −3.'),
('2.2','64','Modular arithmetic and groups','04-spaces','Work with residue classes, not chosen integer representatives. Addition has inverse −a modulo n. For multiplication, ask whether a residue has a multiplicative inverse.','Modulo 5 the nonzero residues have inverses 1↔1, 2↔3, 4↔4. Modulo 8, 2·4 = 0 shows failure of closure on the nonzero residues. For n ≥ 2, prime n makes every nonzero residue coprime to n, and Bézout gives an inverse. A composite n has nonzero factors whose product is 0 modulo n. For n = 1 the nonzero-residue set is empty and is not a group.'),
('2.3','64','A matrix group','04-spaces','Denote a matrix by its three parameters (x,y,z), multiply two generic matrices, then solve for the inverse.','The parameter product is (x+x′, y+y′, z+z′+xy′). Identity is (0,0,0); inverse is (−x,−y,xy−z). Associativity is inherited from matrix multiplication. It is not Abelian: the cross-term xy′ can differ from x′y.'),
('2.4','64–65','Matrix products','02-matrices','Write the shape above each factor before doing arithmetic. For every legal product, compute one row-column pair at a time.','Part (a) is undefined: (3×2)(3×3) has mismatched inner dimensions. Parts (b),(c) give 3×3 arrays; (d) gives 2×2 and (e) gives 4×4. A useful check on (d) is its first entry: 1·0 + 2·1 + 1·2 + 2·5 = 14.'),
('2.5','65','General solutions','03-elimination','Reduce [A | b], check consistency, then set one parameter per non-pivot column.','For each proposed answer p + ∑tᵢzᵢ, verify Ap = b and every Azᵢ = 0. You also need n − rank(A) independent kernel directions to know the answer is complete. In part (b), column 3 is zero, so x₃ must be free if the system is consistent.'),
('2.6','65','A sparse system','03-elimination','Columns 1 and 3 are zero. Read the other equations directly before doing unnecessary elimination.','Set x₁ = s, x₃ = t, x₅ = u. Then x₂ = 2−u, x₄ = −1−u, x₆ = u−1. Thus all solutions are (s,2−u,t,−1−u,u,u−1).'),
('2.7','66','A homogeneous equation with normalization','03-elimination','Move 12x to the left to get (A−12I)x = 0. Only after finding this null space impose the sum of the coordinates.','The third row gives x₂ = 3x₃/2, and the second gives x₁ = 3x₃/2. The sum is 4x₃ = 1. Hence x = (3/8,3/8,1/4). This can be solved with Chapter 2 tools without learning eigenvalues yet.'),
('2.8','66','Inverse or singular?','03-elimination','For part (a), inspect a linear relation between rows. For part (b), row-reduce [A | I].','In (a), row 1 − 2·row 2 + row 3 = 0, so no inverse exists. For any inverse you calculate in (b), verify its product with A is I. The rank test should be completed on the left block, not the entire augmented matrix.'),
('2.9','66','Subspaces and misleading parameters','04-spaces','Ask what values each parameter expression can actually take. μ³ ranges over ℝ; λ² ranges only over the nonnegative reals.','(a) is span{(1,1,1),(0,1,−1)}. (b) is a half-line and fails negative scaling. (c) is a subspace exactly when γ = 0. (d) fails real scalar closure: scaling (0,1,0) by 1/2 leaves the set.'),
('2.10','66','Independence','05-independence','Put the given vectors into columns and look for free variables in Aα = 0.','In (a), the third vector is 2x₁ − x₂, so dependence holds. In (b), the third coordinate forces α₁ = 0; then the second forces α₂ = 0, and the first forces α₃ = 0. Those vectors are independent.'),
('2.11','66','Find combination coefficients','05-independence','Solve [x₁ x₂ x₃]α = y. The unknowns here are coefficients, not components of y.','The coefficients are (−6,3,2). Check: −6(1,1,1) + 3(1,2,3) + 2(2,−1,1) = (1,−2,5).'),
('2.12','67','Intersect spans','06-basis','With generator matrices B₁,B₂, solve B₁α = B₂β, or [B₁ −B₂](α,β) = 0.','Map the resulting parameter solutions through B₁ to obtain actual vectors in the intersection, then remove zero or dependent results. Parameter vectors live in a different space from the intersection itself; returning those coefficient lists is not a basis of U₁ ∩ U₂.'),
('2.13','67','Intersect kernels','09-kernel','A vector lies in both kernels exactly when it solves the system obtained by stacking A₁ above A₂.','Compute dim Uᵢ = 3 − rank(Aᵢ), since the matrices have three columns. Find the intersection from the stacked system, whose solutions also have three entries. This is not the same problem as Exercise 2.14.'),
('2.14','67','Intersect images','09-kernel','Now Uᵢ are column spaces. First find bases from original pivot columns, then use the shared-output method of Exercise 2.12.','These spaces live in ℝ⁴, since the matrices have four rows. Their dimensions equal rank(Aᵢ), not 3 − rank(Aᵢ). Do not stack the matrices as in the kernel exercise: that imposes a different condition.'),
('2.15','67','Implicit and parametric descriptions','10-affine','Substitute (a−b,a+b,a−3b) into x+y−z = 0 to determine which parameters put a point of G into F.','The condition is a + 3b = 0. Substituting a = −3b gives b(−4,−2,−6), so the intersection is span{(2,1,3)}. F has basis (1,0,1),(0,1,1); G has basis (1,1,1),(−1,1,−3). Both are subspaces.'),
('2.16','67–68','Test maps for linearity','07-maps','For function spaces, apply the algebra of integration or differentiation. For a failure, one counterexample is enough.','Integration over fixed bounds and differentiation are linear. Cosine is not, since cos(0) = 1. The remaining maps are multiplication by fixed matrices and are linear. The angle in (e) is fixed for a given map.'),
('2.17','68','Matrix, image, and kernel together','09-kernel','Read each output expression into one matrix row, then row-reduce the resulting 4×3 matrix.','The columns are independent: a 3×3 minor formed from the first three rows has determinant 7. Thus rank = 3, ker Φ = {0}, and the three original columns form a basis of its image. The image has dimension 3 inside ℝ⁴, so the map is injective but not onto ℝ⁴.'),
('2.18','68','Automorphisms and composition','07-maps','Use the stated assumption that both maps are automorphisms: both are already bijective.','Their kernels are {0} and their images are E. Their composition is an automorphism too. All the claimed equalities follow, and {0} ∩ E = {0}. The stronger stated assumptions make this simpler than a general kernel/image composition problem.'),
('2.19','68','One map in a new basis','08-coordinates','Form S from the listed basis vectors in standard coordinates. The requested new matrix is S⁻¹AS.','A is invertible (determinant −2), so its kernel is {0} and image is ℝ³. To verify a computed new matrix, check S Ã = AS column by column. This checks the direction of the coordinate change without another inverse.'),
('2.20','68–69','The full coordinate pipeline','08-coordinates','Keep every coordinate label. If P₁ sends B′ coordinates to B, P₁ = P_B⁻¹P_B′. Here P₂ sends C coordinates to standard coordinates, so P₂ = P_C.','Add and subtract the two given images to find Φ(b₁) = c₁ + 2c₃ and Φ(b₂) = −c₁ + c₂ − c₃. Thus A = [[1,−1],[0,1],[2,−1]] and A′ = P₂AP₁. For the specified x, [x]_B = (8,9), [Φ(x)]_C = (−1,9,7), and the standard output is (6,−11,12). Both routes must give that same output.')]
practice=section('How to use this page','''<p>Close the explanations and try to retrieve the ideas first. If you get stuck, open a hint before opening the reasoning. The exercise guide refers to the problems in your PDF; it does not reproduce the full problem statements. Some entries give final answers; others give a method and checks for completing the calculation yourself.</p><p>You do not need to do all 20 exercises at once. A useful sequence is 2.4 → 2.6 → 2.9 → 2.10 → 2.11 → 2.17 → 2.19 → 2.20. Then work through the group proofs and intersection exercises. Return to the corresponding lesson whenever a method feels like a memorized recipe.</p>''')
practice+=section('One practice problem using the whole chapter','''<p>Consider the map with matrix A below. Find its rank, a basis for its image, its kernel, the condition for Ax = b to be consistent, and all solutions when b = (3,6).</p>'''+eq('A = '+mat([[1,2,-1],[2,4,-2]]))+'''<details><summary>Hint: what does the second row contribute?</summary><p>It is twice the first. There is one pivot and two free variables. Every output must have its second component twice its first.</p></details><details><summary>Full worked solution</summary><p>The rank is 1. The image has basis {(1,2)}, so consistency requires b₂ = 2b₁. The homogeneous equation is x₁ + 2x₂ − x₃ = 0. Set x₂ = s, x₃ = t: the kernel has basis {(-2,1,0),(1,0,1)}.</p><p>For b = (3,6), take p = (3,0,0). Every solution is (3−2s+t,s,t). This is an affine plane in ℝ³ with the kernel as its direction space. Its dimension is 3 − 1 = 2. The map is neither injective nor onto ℝ². Changing coordinates cannot change its rank or make it invertible.</p></details>''')
practice+=section('Five checks before you move on','''<div id="quiz"><p>Choose an answer for each question, then check your reasoning.</p></div><noscript><p>Self-test: explain why full rank need not mean invertible; why pivot columns must come from the original matrix; why kernel vectors live in the domain; why a basis change leaves the vector fixed; and why a bias makes a map affine.</p></noscript>''')
practice+=section('Guide to every book exercise','<label class="search-label">Find an exercise or topic<input id="exercise-search" type="search" placeholder="Try: kernel, groups, 2.20"></label><p id="search-status" role="status"></p><div id="exercise-list">'+''.join(f'<article class="exercise"><h3>{n} · {title}</h3><p class="caption">Printed pp. {pp} · <a href="../mml-book.pdf#page={int(pp.split("–")[0])+6}">Open problem in PDF ↗</a> · <a href="{lesson}.html">Review lesson</a></p><details><summary>First hint</summary><p>{hint}</p></details><details><summary>Reasoning / result checks</summary><p>{answer}</p></details></article>' for n,pp,title,lesson,hint,answer in exercise_data)+'</div>')
practice+=section('Keep these distinctions straight','''<div class="table-wrap"><table><tr><th>Term</th><th>Question it answers</th></tr><tr><td>Span</td><td>What can these vectors build?</td></tr><tr><td>Independence</td><td>Is there a redundant ingredient?</td></tr><tr><td>Basis</td><td>Which ingredients give existence and unique coordinates?</td></tr><tr><td>Dimension</td><td>How many independent directions does this space have?</td></tr><tr><td>Rank</td><td>How many independent output directions does this map reach?</td></tr><tr><td>Kernel / null space</td><td>Which inputs disappear?</td></tr><tr><td>Image / range</td><td>Which outputs are reachable?</td></tr><tr><td>Coordinates</td><td>Which coefficients represent this vector in this ordered basis?</td></tr><tr><td>Affine space</td><td>What happens when a direction space is translated?</td></tr></table></div>''')
practice+=section('Notation decoder','''<p><strong>∀</strong> means “for every”; <strong>∃</strong> means “there exists”; <strong>⊆</strong> means “is a subset of”; <strong>⇔</strong> means “if and only if”; <strong>:=</strong> introduces a definition; <strong>∘</strong> composes functions, rightmost first. A superscript <strong>T</strong> or <strong>ᵀ</strong> is a transpose. A superscript <strong>−1</strong> on an invertible matrix is its inverse. <strong>ker</strong> and <strong>Im</strong> refer to the kernel and image. The book’s <strong>rk</strong> is written <strong>rank</strong> in this guide.</p>''')
add('11-practice','Make it stick','Try the ideas yourself, with hints when you need them.','Exercises · chapter reference','64–69',35,practice,'You can solve a complete problem and explain how elimination, rank, kernel, image, and affine geometry agree.')

from beginner import enhance
primer = enhance(pages, section, eq, mat, box, check)
css='assets/style.css'
def render(p,i):
 nav=''.join(f'<a href="{q["slug"]}.html" '+('aria-current="page" ' if q==p else '')+f'data-page="{q["slug"]}"><span>{j+1:02}</span>{q["title"]}</a>' for j,q in enumerate(pages))
 home=p is None
 title='Linear algebra, made visible' if home else p['title']
 head=f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="description" content="An illustrated, interactive reading companion to Chapter 2 of Mathematics for Machine Learning."><title>{title} · MML Chapter 2</title><link rel="icon" type="image/svg+xml" sizes="any" href="../favicon.svg"><link rel="stylesheet" href="{css}"><script src="assets/app.js" defer></script></head><body data-page="{'index' if home else p['slug']}"><a class="skip" href="#main">Skip to lesson</a><header class="mobile-header"><a href="index.html">MML / CHAPTER 02</a><button id="menu" type="button" aria-expanded="false" aria-controls="sidebar">Lessons</button></header><aside class="sidebar" id="sidebar"><a class="brand" href="index.html"><span class="brand-mark">M<span>+</span></span><span>THE READING ROOM<small>Mathematics for Machine Learning</small></span></a><a class="overview" href="index.html" {'aria-current="page"' if home else ''}>Chapter overview</a><a class="overview" href="00-start.html">00 · Start here: math & English</a><div class="nav-label">YOUR LEARNING PATH</div><nav aria-label="Lessons">{nav}</nav><div class="progress-box"><span id="progress-label">Your progress</span><progress id="progress" max="11" value="0" aria-label="Lessons marked understood"></progress><small>Mark a lesson when you can explain it.</small></div><a class="book-link" href="../mml-book.pdf#page=23">Open Chapter 2 in the book ↗</a></aside><main id="main">'''
 if home:
  body='''<header class="hero"><div class="eyebrow">CHAPTER 02 / A VISUAL READING COMPANION</div><h1>Linear algebra,<br><em>made visible.</em></h1><p class="lede">From solving a pair of equations to seeing what a matrix really does. Build the intuition, follow the mathematics, then try it yourself.</p><div class="hero-actions"><a class="button" href="00-start.html">Start gently <span>→</span></a><a href="11-practice.html">Go to practice</a></div><div class="hero-art" aria-label="A matrix turns the standard basis into two new directions"><svg viewBox="0 0 700 250" role="img" aria-label="Input coordinate grid and its sheared image"><defs><pattern id="grid" width="30" height="30" patternUnits="userSpaceOnUse"><path d="M 30 0 L 0 0 0 30" fill="none" stroke="#cad5cd" stroke-width="1"/></pattern><marker id="arrow" markerWidth="8" markerHeight="8" refX="6" refY="3" orient="auto"><path d="M0,0 L6,3 L0,6" fill="#23786b"/></marker></defs><rect x="20" y="15" width="245" height="210" fill="url(#grid)"/><path d="M80 175 L200 175 M80 175 L80 55" stroke="#23786b" stroke-width="4" marker-end="url(#arrow)"/><text x="95" y="207">A basis</text><text x="310" y="125" font-size="32">A →</text><g transform="translate(425 15) skewX(-20)"><rect width="245" height="210" fill="url(#grid)"/><path d="M60 160 L180 160 M60 160 L60 40" stroke="#23786b" stroke-width="4" marker-end="url(#arrow)"/></g><text x="440" y="242">The same arrows after the map</text></svg></div></header>'''
  body+=section('One chapter. One connected story.','''<p>The central question is <strong>“What can we make by adding vectors and multiplying them by numbers?”</strong> Equations ask for the right coefficients. Independence asks whether those coefficients are unique. A basis gives every vector an address. A linear map moves the vectors, while a basis change only changes their addresses.</p><div class="route"><span>Constraints</span><b>→</b><span>Combinations</span><b>→</b><span>Spaces & bases</span><b>→</b><span>Maps & coordinates</span></div>''')
  body+=section('A reading rhythm that works','''<div class="cards"><article><span class="step-number">01</span><h3>Understand</h3><p>Start with a small example. Learn what each symbol means.</p></article><article><span class="step-number">02</span><h3>Experiment</h3><p>Predict a diagram’s behavior before changing its controls.</p></article><article><span class="step-number">03</span><h3>Try it yourself</h3><p>Answer one question without looking. Then explain your answer in your own words.</p></article></div><p>Start with the <a href="00-start.html">math and English warm-up</a>. Each lesson has a short first-reading path and an English help box. Read for 10–15 minutes at a time. Leave sections marked “second reading” until the main idea feels familiar. A practical schedule is lessons 1–3, then 4–6, then 7–8, then 9–10 with practice between sessions.</p>''')
  body+='<section><h2>Your learning path</h2><div class="lesson-grid">'+''.join(f'<a class="lesson-card" href="{q["slug"]}.html"><span class="eyebrow">{j+1:02} / {q["ref"]}</span><h3>{q["title"]}</h3><p>{q["subtitle"]}</p><span class="caption">{q["minutes"]} min · printed pp. {q["pp"]} <span aria-hidden="true">↗</span></span></a>' for j,q in enumerate(pages))+'</div></section>'
  body+=section('About this companion','''<p>Based on a reading of all of Chapter 2 (printed pp. 17–69, including Exercises 2.1–2.20) in your local <em>Mathematics for Machine Learning</em> PDF by Marc Peter Deisenroth, A. Aldo Faisal, and Cheng Soon Ong, draft dated January 15, 2024. The explanations and diagrams are written for this companion; selected small examples are identified where they follow the book.</p><p>PDF page numbers are six higher than printed numbers in this file, so printed p. 17 is PDF page 23. Every lesson links to its starting page. All diagrams, typography, and interactions work offline, with no external libraries. Progress is stored in this browser when local storage is available; some browsers restrict persistence for local files. The lessons and expandable explanations remain readable without JavaScript.</p><p>The illustrations use ordinary 2D coordinates for intuition. Lengths and angles are not the focus until Chapter 3. The practice guide includes hints and selected results, rather than a complete solutions manual.</p>''')
 else:
  body=f'<header class="lesson-header"><div class="eyebrow">LESSON {i+1:02} / {p["ref"]}</div><h1>{p["title"]}</h1><p class="lede">{p["subtitle"]}</p><div class="meta"><span>About {p["minutes"]} minutes</span><a href="../mml-book.pdf#page={int(p["pp"].split("–")[0])+6}">Book pp. {p["pp"]} ↗</a></div><div class="goal"><strong>By the end</strong><p>{p["take"]}</p></div></header>'
  body+='<nav class="on-this-page" aria-label="On this page"><strong>IN THIS LESSON</strong><div id="section-links"></div></nav>'+p['body']
  body+=f'<section class="finish"><h2>Can you explain it without looking?</h2><p>{p["take"]}</p><button type="button" id="mark-done" aria-pressed="false">Mark as understood</button><span id="saved-status" role="status"></span></section>'
  prev=pages[i-1] if i>0 else None
  nxt=pages[i+1] if i+1<len(pages) else None
  body+='<nav class="page-nav" aria-label="Previous and next lesson"><a href="'+(prev['slug']+'.html' if prev else 'index.html')+'">← '+(prev['title'] if prev else 'Chapter overview')+'</a><a href="'+(nxt['slug']+'.html' if nxt else 'index.html')+'">'+(nxt['title'] if nxt else 'Back to chapter overview')+' →</a></nav>'
 if p is primer: head=head.replace('class="overview" href="00-start.html"', 'class="overview" href="00-start.html" aria-current="page"')
 return head+body+'<footer>MML / CHAPTER 02 <span>Read slowly. Test an idea. Connect it to the next.</span></footer></main></body></html>'
for i,p in enumerate(pages): (ROOT/(p['slug']+'.html')).write_text(render(p,i))
(ROOT/'00-start.html').write_text(render(primer,-1).replace('<button type="button" id="mark-done" aria-pressed="false">Mark as understood</button>', '<a class="button" href="01-systems.html">Continue to the first lesson →</a>'))
(ROOT/'index.html').write_text(render(None,-1))
print(f'Built {len(pages)+2} HTML pages')
